version: '3'

services:

  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: intensivo_nestjs
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    build: .docker/postgres
    container_name: intensivo_nestjs_db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=intensivo_nestjs

  pgadmin:
    image: dpage/pgadmin4
    container_name: intensivo_nestjs_db_adm
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80
    depends_on:
      - db
