PUT http://localhost:3000/products/5
Content-Type: application/json

{
  //"name": "Alterei via PUT",
  "price": 309.32
}
###

DELETE http://localhost:3000/products/2
###

GET http://localhost:3000/products/4
###

GET http://localhost:3000/products
###

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Mais Um Produto teste",
  "price": 109.22
}
###